language: c
sudo: false
addons:
  apt:
    packages:
    - gawk
    - gnupg
    - graphicsmagick
    - graphicsmagick
    - m4
    - noweb
    - ocaml
    - ocaml-findlib
    - texlive-font-utils
    - texlive-lang-french
    - texlive-latex-base
install: sh -ex ./Library/Ancillary/autoinstall bmake
script: sh -ex ./Library/Ancillary/travisci
